In [10]:
from scipy.linalg import toeplitz
import scipy.linalg as la
import numpy as np

In [5]:
#create a 6 by 6 second difference constant-diagonal matrix K
K = toeplitz([2,-1,0,0,0,0])
K

array([[ 2, -1,  0,  0,  0,  0],
       [-1,  2, -1,  0,  0,  0],
       [ 0, -1,  2, -1,  0,  0],
       [ 0,  0, -1,  2, -1,  0],
       [ 0,  0,  0, -1,  2, -1],
       [ 0,  0,  0,  0, -1,  2]])

In [6]:
# get the LU decomposition of K
P,L,U = la.lu(K)

In [14]:
print(L)

[[ 1.          0.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.          0.        ]
 [ 0.          0.          0.         -0.8         1.          0.        ]
 [ 0.          0.          0.          0.         -0.83333333  1.        ]]


In [15]:
#inverse of L
print(np.linalg.inv(L))

[[ 1.         -0.         -0.         -0.         -0.         -0.        ]
 [ 0.5         1.         -0.          0.         -0.         -0.        ]
 [ 0.33333333  0.66666667  1.         -0.          0.          0.        ]
 [ 0.25        0.5         0.75        1.         -0.          0.        ]
 [ 0.2         0.4         0.6         0.8         1.         -0.        ]
 [ 0.16666667  0.33333333  0.5         0.66666667  0.83333333  1.        ]]


The parttern is for $i < j$, the $ij^{th}$ entry = $i/j$

In [16]:
print(np.linalg.inv(K))

[[ 0.85714286  0.71428571  0.57142857  0.42857143  0.28571429  0.14285714]
 [ 0.71428571  1.42857143  1.14285714  0.85714286  0.57142857  0.28571429]
 [ 0.57142857  1.14285714  1.71428571  1.28571429  0.85714286  0.42857143]
 [ 0.42857143  0.85714286  1.28571429  1.71428571  1.14285714  0.57142857]
 [ 0.28571429  0.57142857  0.85714286  1.14285714  1.42857143  0.71428571]
 [ 0.14285714  0.28571429  0.42857143  0.57142857  0.71428571  0.85714286]]


In [17]:
# 7 * inverse of K
print(7 * np.linalg.inv(K))

[[  6.   5.   4.   3.   2.   1.]
 [  5.  10.   8.   6.   4.   2.]
 [  4.   8.  12.   9.   6.   3.]
 [  3.   6.   9.  12.   8.   4.]
 [  2.   4.   6.   8.  10.   5.]
 [  1.   2.   3.   4.   5.   6.]]


In [20]:
# (k)(7inv(k)) = 7I
print(K.dot(7 * np.linalg.inv(K)))

[[  7.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [ -1.77635684e-15   7.00000000e+00   0.00000000e+00   0.00000000e+00
    1.77635684e-15   8.88178420e-16]
 [  0.00000000e+00   0.00000000e+00   7.00000000e+00   0.00000000e+00
   -3.55271368e-15  -1.77635684e-15]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   7.00000000e+00
    3.55271368e-15   1.77635684e-15]
 [  4.44089210e-16   8.88178420e-16   0.00000000e+00   0.00000000e+00
    7.00000000e+00   1.77635684e-15]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.77635684e-15
    0.00000000e+00   7.00000000e+00]]
